typography_spectrum: 0.8784761196002364
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.17046033078804612
  lightness: 0.9861960986163467
  saturation: 0.7119383176323026
  rhythmicContrast: 0.35945953195914626
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00879950262606144
analytics:
  google: null
  facebook: null
  twitter: null
name: Sleep Better
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hack your sleep
purpose: []
